language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # - "3.8-dev"  # 3.8 development branch
  # - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python main.py examples/cube/cube.obj examples/cube/texture-bad-background.png --output examples/cube/travis-results.png
  - python tests/compare_images.py examples/cube/texture-bad-background-erased.png examples/cube/travis-results.png
